src/AppBundle/Entity/Book.php
<?php
/**
 * Created by PhpStorm.
 * User: fominsk
 * Date: 10.10.2016
 * Time: 15:30
 */

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;

/**
 * Class Book
 * @ORM\Table(name="books")
 * @ORM\Entity()
 * @Gedmo\SoftDeleteable(fieldName="deletedAt")
 */
class Book
{
    use SoftDeleteableEntity;

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=254)
     * @Assert\NotBlank(groups={"creation", "edition"})
     * @Assert\Length(min=1, max=150, groups={"creation", "edition"})
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Author", inversedBy="books")
     */
    private $authors;
    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Genre", inversedBy="books")
     */
    private $genres;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(groups={"creation", "edition"})
     * @Assert\Length(min=1, max=1024, groups={"creation", "edition"})
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\BookHistory", mappedBy="book")
     */
    private $bookHistory;

    public function __construct()
    {
        $this->authors = new ArrayCollection();
        $this->genres = new ArrayCollection();
        $this->bookHistory = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getAuthors()
    {
        return $this->authors;
    }

    /**
     * @param mixed $authors
     */
    public function setAuthors($authors)
    {
        $this->authors = $authors;
    }

    /**
     * @return mixed
     */
    public function getGenres()
    {
        return $this->genres;
    }

    /**
     * @param mixed $genres
     */
    public function setGenres($genres)
    {
        $this->genres = $genres;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    public function getBookAuthors()
    {
        $authors = '';
        /** @var Author $author */
        foreach ($this->authors as $author)
        {
            $authors .= $author->getName().', ';
        }

        return rtrim($authors,', ');
    }

    public function getBookGenres()
    {
        $genres = '';
        /** @var Genre $genre */
        foreach ($this->genres as $genre)
        {
            $genres .= $genre->getName().', ';
        }

        return rtrim($genres,', ');
    }

    /**
     * @return mixed
     */
    public function getBookHistory()
    {
        return $this->bookHistory;
    }

    /**
     * @param mixed $bookHistory
     */
    public function setBookHistory($bookHistory)
    {
        $this->bookHistory = $bookHistory;
    }


}

src/AppBundle/Entity/BookHistory.php
<?php
/**
 * Created by PhpStorm.
 * User: fominsk
 * Date: 07.12.2016
 * Time: 10:30
 */

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Class Book
 * @ORM\Table(name="book_history")
 * @ORM\Entity()
 */
class BookHistory
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Book", inversedBy="bookHistory")
     * @ORM\JoinColumn(name="book_id", referencedColumnName="id", nullable=false)
     * @Assert\NotBlank(groups={"creation", "edition"})
     */
    private $book;

    /**
     * @ORM\Column(type="datetime")
     */
    private $issue_date;

    /**
     * @ORM\Column(type="date")
     */
    private $due_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $return_date;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Reader", inversedBy="bookHistory")
     * @ORM\JoinColumn(name="reader_id", referencedColumnName="id", nullable=false)
     * @Assert\NotBlank(groups={"creation", "edition"})
     */
    private $reader;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User", inversedBy="bookHistory")
     */
    private $librarian;

    public function __construct()
    {
        $this->issue_date = new \DateTime('now');
        $this->due_date = new \DateTime('now');
        $this->due_date->modify('+2 week');
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getBook()
    {
        return $this->book;
    }

    /**
     * @param mixed $book
     */
    public function setBook($book)
    {
        $this->book = $book;
    }

    /**
     * @return mixed
     */
    public function getIssueDate()
    {
        return $this->issue_date;
    }

    /**
     * @param mixed $issue_date
     */
    public function setIssueDate($issue_date)
    {
        $this->issue_date = $issue_date;
    }

    /**
     * @return mixed
     */
    public function getDueDate()
    {
        return $this->due_date;
    }

    /**
     * @param mixed $due_date
     */
    public function setDueDate($due_date)
    {
        $this->due_date = $due_date;
    }

    /**
     * @return mixed
     */
    public function getReturnDate()
    {
        return $this->return_date;
    }

    /**
     * @param mixed $return_date
     */
    public function setReturnDate($return_date)
    {
        $this->return_date = $return_date;
    }

    /**
     * @return mixed
     */
    public function getReader()
    {
        return $this->reader;
    }

    /**
     * @param mixed $reader
     */
    public function setReader($reader)
    {
        $this->reader = $reader;
    }

    /**
     * @return mixed
     */
    public function getLibrarian()
    {
        return $this->librarian;
    }

    /**
     * @param mixed $librarian
     */
    public function setLibrarian($librarian)
    {
        $this->librarian = $librarian;
    }



}

src/AppBundle/Controller/BookController.php
<?php
/**
 * Created by PhpStorm.
 * User: fominsk
 * Date: 10.10.2016
 * Time: 15:21
 */

namespace AppBundle\Controller;

use AppBundle\Entity\Author;
use AppBundle\Entity\Book;
use AppBundle\Form\BookForm;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\Query\Expr;

class BookController extends Controller
{
    /**
     * @Route("/books", name="books", methods={"GET"})
     */
    public function indexAction()
    {
        return $this->render('AppBundle:Book:index.html.twig');
    }

    /**
     * @Route("/books/add", name="books-add",methods={"GET", "POST"})
     */
    public function addAction(Request $request)
    {
        $form = $this->createForm( BookForm::class, new Book(), array('validation_groups' => array('creation'), 'locale' => $request->getLocale()) );

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $object = $form->getData();
                $em = $this->getDoctrine()->getManager();
                $em->persist($object);
                $em->flush();
                return $this->redirectToRoute('books');
            }
        }

        return $this->render('AppBundle:Book:add.html.twig',array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/books/edit/{id}", name="books-edit",methods={"GET", "POST"}, requirements={"id" = "\d+"})
     */
    public function editAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $object = $em->find('AppBundle:Book',$id);
        $form = $this->createForm( BookForm::class, $object, array('validation_groups' => array('edition'), 'locale' => $request->getLocale()));

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $object = $form->getData();
                $em->merge($object);
                $em->flush();
                return $this->redirectToRoute('books');
            }
        }

        return $this->render('AppBundle:Book:edit.html.twig',array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/books/delete/{id}", name="books-delete",methods={"GET", "POST"}, requirements={"id" = "\d+"})
     */
    public function deleteAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $object = $em->find('AppBundle:Book',$id);
        $token = $this->get('security.csrf.token_manager');
        if ($request->isMethod('POST')) {
            if ($request->get('token_') === $token->getToken('delete')->getValue()) {
                $em->remove($object);
                $em->flush();
            }
            return $this->redirectToRoute('books');
        }

        return $this->render('AppBundle:Book:delete.html.twig',array(
            'object' => $object,
            'token' => $token->refreshToken('delete'),
            'id' => $id
        ));
    }


    /**
     * @Route("/books/ajax/getBooksTable", name="ajax_get_books_table", methods={"POST"}, condition="request.isXmlHttpRequest()")
     */
    public function ajaxGetBooksTable(Request $request)
    {
        $result = array();
        $result['draw'] = $request->get('draw');
        $offset = $request->get('start');
        $limit = $request->get('length');
        $order = $request->get('order');
        $search_ = $request->get('search');
        $searchValue = mb_strtolower($search_['value']);
        $columns = $request->get('columns');

        $orderColumn = $columns[$order[0]['column']]['name'];
        $orderDirection = strtoupper($order[0]['dir']);

        $em = $this->getDoctrine()->getEntityManager();

        $con = $em->getConnection();
        $search = '%'.$searchValue.'%';
        $where = 'WHERE b0_.deleted_at IS NULL';
        if (!empty($searchValue)) {
            $where .= ' AND (LOWER(b0_.name) LIKE :search OR ba0_.author_id IN (SELECT a2_.id FROM authors AS a2_ WHERE LOWER(a2_.name) LIKE :search))';
        }

        $query = "SELECT DISTINCT b0_.*,
bh0_.issue_date AS book_availability,
(SELECT string_agg(DISTINCT a1_.name,',') FROM book_author AS ba1_ INNER JOIN authors AS a1_ ON (a1_.id = ba1_.author_id) WHERE ba1_.book_id = b0_.id) as authors,
(SELECT string_agg(DISTINCT g1_.name,',') FROM book_genre AS bg1_ INNER JOIN genres AS g1_ ON (g1_.id = bg1_.genre_id) WHERE bg1_.book_id = b0_.id) as genres
FROM books AS b0_
INNER JOIN book_author AS ba0_ ON (ba0_.book_id = b0_.id)
INNER JOIN book_genre AS bg0_ ON (bg0_.book_id = b0_.id)
LEFT JOIN book_history AS bh0_ ON (bh0_.book_id = b0_.id AND bh0_.return_date IS NULL)
".$where."
GROUP BY b0_.id, ba0_.author_id, bh0_.id
ORDER BY ".$orderColumn.' '.$orderDirection . ' LIMIT ' . $limit . ' OFFSET '.$offset;

        $stmt = $con->prepare($query);

        if (!empty($searchValue)) {
        $stmt->bindValue('search',$search);
        }
        $stmt->execute();
        $objects = $stmt->fetchAll();

        $result['query'] = $query;


        $data = array();
        $translator = $this->container->get('translator');
        /**
         * @var Book $object
         */
        foreach ($objects as $object) {
            $options = '<div class="btn-group btn-group-xs" role="group" aria-label="...">';
            $options .= '<a href="'.$this->generateUrl('books-info',array( "id" => $object['id'] )).'" class="btn btn-default"><i class="fa fa-info-circle"></i></a>';
            $options .= '<a href="'.$this->generateUrl('books-edit',array( "id" => $object['id'] )).'" class="btn btn-default"><i class="fa fa-edit"></i></a>';
            $options .= '<a href="'.$this->generateUrl('books-delete',array( "id" => $object['id'] )).'" class="btn btn-default cancel"><i class="fa fa-trash-o"></i></a>';
            $options .= '</div>';

            if ($object['book_availability'] === null) {
                $status = '<span class="label label-success">'.$translator->trans('label.available').'</span>';
            } else {
                $status = '<span class="label label-danger">'.$translator->trans('label.issued').'</span>';
            }

            $data[] = array(
                $object['id'],
                $object['name'],
                $object['authors'],
                $object['genres'],
                $status,
                $options
            );
        }
        $qb = null;
        $qb = $em->createQueryBuilder();
        $result['recordsTotal'] = $qb->select('count(b.id)')->from('AppBundle:Book', 'b')->getQuery()->getSingleScalarResult();
        $query = $qb->getQuery()->getSQL();
        $query = str_replace(',', ",<br>",$query);
        $query = str_replace('FROM', "<br>FROM",$query);
        $query= str_replace('WHERE', "<br>WHERE",$query);
        $query= str_replace('ORDER', "<br>ORDER",$query);
        $query= str_replace('INNER', "<br>INNER",$query);
        $result['query'] .= '<br><br>'.$query;
        if ($searchValue !== '') {

            $query = "SELECT count(*) AS filtered_row_count 
FROM (SELECT count(DISTINCT b0_.id)
FROM books AS b0_
INNER JOIN book_author AS ba0_ ON (ba0_.book_id = b0_.id)
INNER JOIN authors AS a0_ ON (a0_.id = ba0_.author_id)
".$where."
GROUP BY b0_.id
) as num";


            $stmt = $con->prepare($query);
            if (!empty($searchValue)) {
                $stmt->bindValue('search',$search);
            }
            $stmt->execute();
            $count = $stmt->fetchColumn(0);
            $result['recordsFiltered'] = $count;


            $result['query'] .= '<br><br>'.$query;
        } else {
            $result['recordsFiltered'] = $result['recordsTotal'];
        }
        $result['data'] = $data;

        return new JsonResponse($result);
    }

    /**
     * @Route("/books/ajax/getBooksList", name="ajax_get_books_list", methods={"GET"}, condition="request.isXmlHttpRequest()")
     */
    public function ajaxGetBookList(Request $request)
    {
        $result = array();
        $limit = filter_var($request->get('page_limit'),FILTER_SANITIZE_NUMBER_INT);

        $em = $this->getDoctrine()->getEntityManager();

        $qb = $em->createQueryBuilder();

        $qb->select('b')
            ->from('AppBundle:Book','b')->leftJoin('b.bookHistory', 'bh');
        if (ctype_digit($request->get('q'))) {
            $search = (int)filter_var(mb_strtolower($request->get('q')),FILTER_SANITIZE_NUMBER_INT);
            $qb->where('b.id = :search');
        } else {
            $search = '%'.filter_var(mb_strtolower($request->get('q')),FILTER_SANITIZE_STRING).'%';
            $qb->where('LOWER(b.name) LIKE :search');
        }
        $qb->setParameter('search',$search)->andWhere('(bh.return_date IS NOT NULL AND bh.issue_date IS NOT NULL) OR (bh.return_date IS NULL AND bh.issue_date IS NULL)')
            ->orderBy('b.name','ASC')
            ->setMaxResults($limit);

        $objects = $qb->getQuery()->getResult();
        /** @var Book $object */
        foreach ($objects as $object)
        {
            $result[] = array(
                'id' => $object->getId(),
                'text' => '[' . $object->getId() . '] ' . $object->getName() . ' ('. $object->getBookAuthors() . ')'
            );
        }

        return new JsonResponse($result);
    }

    /**
     * @Route("/books/info/{id}", name="books-info",methods={"GET", "POST"}, requirements={"id" = "\d+"})
     */
    public function infoAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $qb = $em->createQueryBuilder();

        $qb->select('b','bh','r')
            ->from('AppBundle:Book','b')
            ->leftJoin('b.bookHistory','bh', Expr\Join::WITH, 'bh.return_date IS NULL')

src/AppBundle/Resources/views/Book/add.html.twig
{% extends "AppBundle::layout.html.twig" %}

{% block css %}
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet">
    <link href="//raw.githubusercontent.com/t0m/select2-bootstrap-css/bootstrap3/select2-bootstrap.min.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 60px;">
        <div class="page-header">
            <h3><i class="fa fa-book"></i> {% trans %}label.new_book{% endtrans %}</h3>
        </div>
        <div class="row">
            <div class="col-md-6">
                {% form_theme form 'bootstrap_3_layout.html.twig' %}
                {{ form_start(form) }}
                {{ form_widget(form) }}
                {% include "@App/_form-buttons.html.twig" with {'url': 'books'} %}

                {{ form_end(form) }}
            </div>
        </div>

    </div>
{% endblock %}
{% block js %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/i18n/ru.js"></script>
    <script src="{{ asset('bundles/tetranzselect2entity/js/select2entity.js') }}"></script>
{% endblock %}

src/AppBundle/Resources/views/Book/delete.html.twig
{% extends "AppBundle::layout.html.twig" %}


{% block content %}
    <div class="container" style="margin-top: 60px;">
        <div class="page-header">
            <h3><i class="fa fa-trash-o"></i> {% trans %}label.data_deletion{% endtrans %}</h3>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-default panel-danger">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-exclamation-triangle"></i> {% trans %}message.data.deletion{% endtrans %}</h3>
                    </div>
                    <div class="panel-body">
                        <p>&nbsp;</p>
                        <p style="text-align: center">{% trans %}label.book_deletion{% endtrans %} {{ object.name }}?</p>
                        <p>&nbsp;</p>
                        <div class="row">
                            <div class="col-md-6"><a href="{{ path('books') }}" class="btn btn-default"><i class="fa fa-ban"></i> {% trans %}label.cancel{% endtrans %}</a></div>
                            <form method="post" action="{{ path('books-delete', {'id': id}) }}">
                                <input type="text" hidden="hidden" name="token_" value="{{ token }}" />
                                <div class="col-md-6"><button class="btn btn-danger pull-right"><i class="fa fa-trash-o"></i> {% trans %}label.delete{% endtrans %}</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

src/AppBundle/Resources/views/Book/edit.html.twig
{% extends "AppBundle::layout.html.twig" %}

{% block css %}
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet">
    <link href="//raw.githubusercontent.com/t0m/select2-bootstrap-css/bootstrap3/select2-bootstrap.min.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 60px;">
        <div class="page-header">
            <h3><i class="fa fa-edit"></i> {% trans %}label.edit.book{% endtrans %}</h3>
        </div>
        <div class="row">
            <div class="col-md-6">
                {% form_theme form 'bootstrap_3_layout.html.twig' %}
                {{ form_start(form) }}
                {{ form_widget(form) }}
                {% include "@App/_form-buttons.html.twig" with {'url': 'books'} %}

                {{ form_end(form) }}
            </div>
        </div>

    </div>
{% endblock %}
{% block js %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/i18n/ru.js"></script>
    <script src="{{ asset('bundles/tetranzselect2entity/js/select2entity.js') }}"></script>
{% endblock %}

src/AppBundle/Resources/views/Book/index.html.twig
{% extends 'AppBundle::layout.html.twig' %}
{% block css %}
    <style>
        #object-table { table-layout: fixed; }
        #object-table td {
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
            -o-text-overflow: ellipsis;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid" style="margin-top: 60px;">
        <div class="page-header"><h3><i class="fa fa-book"></i> {% trans %}label.books{% endtrans %}{% include 'AppBundle::_queryButton.html.twig' %} </h3></div>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered table-striped table-hover table-condensed" id="object-table">
                    <thead>
                    <tr>
                        <th>{% trans %}label.number{% endtrans %}</th>
                        <th>{% trans %}label.name{% endtrans %}</th>
                        <th>{% trans %}label.authors{% endtrans %}</th>
                        <th>{% trans %}label.genres{% endtrans %}</th>
                        <th>{% trans %}label.status{% endtrans %}</th>
                        <th class="no-sort">&nbsp;</th>
                    </tr>
                    </thead>
                </table>
                <a href="{{ path('books-add') }}" class="btn btn-success"><i class="fa fa-plus"></i> {% trans %}label.add{% endtrans %}</a>
            </div>
        </div>
        <br>
        {{ include('AppBundle::_panel-sql.html.twig',{queryId: 'query', query: ''}) }}
    </div>
{% endblock %}
{% block js %}
    {% include 'AppBundle::_toggleQueryBlock.html.twig' %}
    <script>
        $(function () {
            var table = $('#object-table').DataTable({
                "serverSide": true,
                "processing": true,
                "stateSave": true,
                "order": [[0,"ASC"]],
                "iDisplayLength": 25,
                "sPaginationType": "full_numbers",
                "responsive": true,
                "columnDefs": [{
                    "targets": "no-sort",
                    "orderable": false,
                    "searchable": false
                }],
                "language": {
                    "url": '//cdn.datatables.net/plug-ins/1.10.12/i18n/{{ table_language }}.json'
                },

                "ajax": {
                    "url": "{{ path('ajax_get_books_table') }}",
                    "type": "POST",
                    "dataSrc": function (json) {

                        $('#query').empty().append(json.query);
                        return json.data;
                    }
                },
                "columns": [
                    { "name": "id", 'width': '5%'},
                    { "name": "name"},
                    { "name": "authors"},
                    { "name": "genres"},
                    { "name": "book_availability"},
                    { "name": "options", 'width': '55px' }
                ]
            });
        });
    </script>
{% endblock %}

src/AppBundle/Resources/views/Book/info.html.twig
{% extends "AppBundle::layout.html.twig" %}

{% block css %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
{% endblock %}
{% block content %}
    <div class="container" style="margin-top: 60px;">
        <div class="page-header">
            <h3><i class="fa fa-info-circle"></i> {% trans %}label.book.info{% endtrans %} {% include 'AppBundle::_queryButton.html.twig' %}</h3>
        </div>
        <div class="row">
            <div class="col-md-7">
                <div class="panel panel-primary">
                    <div class="panel-heading"><i class="fa fa-info-circle"></i> {% trans %}label.book{% endtrans %}</div>
                    <table class="table">
                        <tr><td>{% trans %}label.number{% endtrans %}</td><td>{{ object.id }}</td></tr>
                        <tr><td>{% trans %}label.name{% endtrans %}</td><td>{{ object.name }}</td></tr>
                        <tr><td>{% trans %}label.authors{% endtrans %}</td><td>{{ object.bookAuthors}}</td></tr>
                        <tr><td>{% trans %}label.genres{% endtrans %}</td><td>{{ object.bookGenres }}</td></tr>

                        {% if history and history.returnDate is null %}
                            <tr><td>{% trans %}label.status{% endtrans %}</td><td><span class="label label-danger">{% trans %}label.issued{% endtrans %}</span></td></tr>
                            <tr><td>{% trans %}label.reader{% endtrans %}</td><td>{{ history.reader.name }} {{ history.reader.surname }}</td></tr>
                        {% else %}
                            <tr><td>{% trans %}label.status{% endtrans %}</td><td><span class="label label-success">{% trans %}label.available{% endtrans %}</span></td></tr>
                        {% endif %}

                        <tr><td>{% trans %}label.description{% endtrans %}</td><td>{{ object.description }}</td></tr>


                    </table>
                </div>
                {{ include('AppBundle::_panel-sql.html.twig',{queryId: 'query1'}) }}
            </div>
            <div class="col-md-5">
                <div class="panel panel-info">
                    <div class="panel-heading"><i class="fa fa-bar-chart-o"></i> {% trans %}label.book.graph{% endtrans %}</div>
                    <div class="panel-body">
                        <div id="stats-container" style="max-height: 150px;"></div>
                    </div>
                </div>
                {{ include('AppBundle::_panel-sql.html.twig',{queryId: 'query2', query: ''}) }}
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-success">
                    <div class="panel-heading"><i class="fa fa-archive"></i> {% trans %}label.reader.history{% endtrans %}</div>
                    <div class="panel-body">
                        <table class="table table-bordered table-striped table-hover table-condensed" id="issued-book-history-table">
                            <thead>
                            <tr>
                                <th>{% trans %}label.book{% endtrans %}</th>
                                <th>{% trans %}label.issue.date{% endtrans %}</th>
                                <th>{% trans %}label.status{% endtrans %}</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
                {{ include('AppBundle::_panel-sql.html.twig',{queryId: 'query3', query: ''}) }}
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <a href="{{ path('books') }}" class="btn btn-default"><i class="fa fa-arrow-left"></i> {% trans %}label.back{% endtrans %}</a>
            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
    {% include 'AppBundle::_toggleQueryBlock.html.twig' %}
    <script>
        $(function () {

            var table = $('#issued-book-history-table').DataTable({
                "serverSide": true,
                "processing": true,
                "responsive": true,
                "iDisplayLength": 25,
                //"paging":   false,
                "ordering": false,
                "info":     false,
                "searching": false,
                "language": {
                    "url": '//cdn.datatables.net/plug-ins/1.10.12/i18n/{{ table_language }}.json'
                },
                "ajax": {
                    "url": "{{ path('ajax_get_book_readers_history_table') }}",
                    "type": "POST",
                    "data": { "id": "{{ object.id }}"},
                    "dataSrc": function (json) {

                        $('#query3').empty().append(json.query);
                        return json.data;
                    }
                }
            });

            $('#stats-container').append('{% include 'AppBundle::_spinner.html.twig' %}');
            $.ajax({
                dataType: "json",
                data: {id: "{{ object.id }}"},
                type: "POST",
                url: "{{ path('ajax_get_book_stats') }}"
            }).done(function (data) {
                $('#stats-container').empty();
                if (data.data.length > 0 ){
                    var chart = Morris.Line({
                        element: 'stats-container',
                        data: data.data,
                        xkey: 'month',
                        ykeys: ['count'],
                        labels: ['Books']
                    });
                } else {
                    $('#stats-container').append('{% include 'AppBundle::_no-data.html.twig' %}');
                }
                $('#query2').empty().append(data.query);

            });

        });
    </script>
{% endblock %}